name 'thbe-rkhunter'
version '0.1.0'

author 'Thomas Bendler <project@bendler-net.de>'
license 'GPLv3'
project_page 'https://github.com/thbe/puppet-rkhunter.git'
source 'https://github.com/thbe/puppet-rkhunter.git'
summary 'Rkhunter management module'
description 'Rkhunter management module'
dependency 'puppetlabs/stdlib', '>=4.1.0'
